--[[ 
Example Usage of ISFOR's Drag System

Steps:
1. Place the DragSystem ModuleScript in ReplicatedStorage.
2. Rename your draggable part to "DraggablePart" (or update the script to reference the correct part).
3. or place the "DraggablePart" inside of the workspace OR Creat a New One Then Named to DraggablePart Or Change it from The Module script Feel Free
4. Place Drag in StarterPlayerScripts.
--]]